name: Build
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: Swatinem/rust-cache@v2.7.7
            - name: Rust Cache
            - uses: rust-build/rust-build.action@v1.4.5
            - name: Rust Release binary
