name: release
on:
  release:
    types:
      - created
jobs:
  release:
    name: 'release ${{ matrix.target }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-pc-windows-msvc
          - target: x86_64-unknown-linux-musl
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: lxl66566/rust-simple-release@main
        with:
          targets: aarch64-unknown-linux-gnu, aarch64-unknown-linux-musl, x86_64-pc-windows-msvc, x86_64-unknown-linux-musl, x86_64-unknown-linux-gnu, aarch64-apple-darwin, x86_64-apple-darwin
          token: '${{ secrets.GH_TOKEN }}'
